# Generated by Django 5.2.2 on 2025-09-12 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('test', 'test'), ('sub', 'Subscription')], default='sub', max_length=10)),
                ('sub_link', models.CharField(max_length=255)),
                ('day_limit', models.IntegerField(blank=True, null=True)),
                ('traffic_limit', models.IntegerField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_test', models.BooleanField(default=False)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='subs.subscriptionlinks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
