# Generated by Django 5.2.2 on 2025-09-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlinks',
            name='day_limit',
            field=models.IntegerField(default=1, help_text='Unlimited=0'),
            preserve_default=False,
        ),
    ]
