# Generated by Django 5.2.2 on 2025-09-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0002_alter_subscriptionlinks_day_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionlinks',
            name='traffic_limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
