# Generated by Django 5.2.2 on 2025-09-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0003_alter_subscriptionlinks_traffic_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionlinks',
            options={'verbose_name': 'Subscription link', 'verbose_name_plural': 'Subscription links'},
        ),
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterField(
            model_name='subscriptionlinks',
            name='day_limit',
            field=models.IntegerField(help_text='Unlimited=0', verbose_name='Day limit'),
        ),
        migrations.AlterField(
            model_name='subscriptionlinks',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Is test'),
        ),
        migrations.AlterField(
            model_name='subscriptionlinks',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Is used'),
        ),
        migrations.AlterField(
            model_name='subscriptionlinks',
            name='plan_type',
            field=models.CharField(choices=[('test', 'Test'), ('sub', 'Subscription')], default='sub', max_length=10, verbose_name='Plan type'),
        ),
        migrations.AlterField(
            model_name='subscriptionlinks',
            name='sub_link',
            field=models.CharField(max_length=255, verbose_name='Subscription link'),
        ),
        migrations.AlterField(
            model_name='subscriptionlinks',
            name='traffic_limit',
            field=models.IntegerField(verbose_name='Traffic limit'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expire date'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='Is test'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='subs.subscriptionlinks', verbose_name='Subscription link'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
