# Generated by Django 5.2.2 on 2025-09-18 10:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyAskedQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='question')),
            ],
            options={
                'verbose_name': 'FrequentlyAskedQuestion',
                'verbose_name_plural': 'FrequentlyAskedQuestions',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name1', models.CharField(max_length=55, verbose_name='site name1')),
                ('site_name2', models.CharField(max_length=55, verbose_name='site name2')),
                ('site_logo', models.ImageField(upload_to='logo/', verbose_name='site logo')),
                ('payment_card', models.CharField(max_length=155, verbose_name='payment card number')),
                ('payment_card_name', models.CharField(max_length=155, verbose_name='payment card owner name')),
                ('up_time', models.CharField(max_length=55, verbose_name='servers uptime')),
                ('countries_count', models.CharField(max_length=55, verbose_name='countries count')),
                ('servers_count', models.CharField(max_length=55, verbose_name='servers count')),
                ('footer_text', models.CharField(max_length=155, verbose_name='footer text')),
                ('users_count_for_about_us', models.CharField(max_length=55, verbose_name='users_count_for_about_us')),
                ('established_year_for_about_us', models.CharField(max_length=55, verbose_name='established_year_for_about_us')),
                ('feature1_for_about_us', models.CharField(max_length=55, verbose_name='feature1_for_about_us')),
                ('feature2_for_about_us', models.CharField(max_length=55, verbose_name='feature2_for_about_us')),
                ('feature3_for_about_us', models.CharField(max_length=55, verbose_name='feature3_for_about_us')),
                ('feature4_for_about_us', models.CharField(max_length=55, verbose_name='feature4_for_about_us')),
                ('telegram_support_id_link', models.URLField(verbose_name='telegram_support_id_link')),
                ('telegram_Channel_id_link', models.URLField(verbose_name='telegram_Channel_id_link')),
                ('telegram_bot_id_link', models.URLField(verbose_name='telegram_bot_id_link')),
            ],
            options={
                'verbose_name': 'SiteSetting',
                'verbose_name_plural': 'SiteSettings',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='username')),
                ('phone', models.CharField(max_length=32, unique=True, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='full name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='is phone verified')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telegram_id', models.CharField(blank=True, max_length=55, verbose_name='telegram id')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='core.frequentlyaskedquestions', verbose_name='question')),
            ],
        ),
    ]
