# Generated by Django 5.2.2 on 2025-09-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(default='Dfbndf', max_length=55),
            preserve_default=False,
        ),
    ]
