# Generated by Django 6.0.7 on 2026-07-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='phone'),
        ),
    ]
