# Generated by Django 5.2.13 on 2026-07-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_balance',
            field=models.PositiveIntegerField(default=0, verbose_name='wallet balance'),
        ),
    ]
