# Generated by Django 5.2.2 on 2025-09-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_card',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
