# Generated by Django 5.2.2 on 2025-09-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name1', models.CharField(max_length=55)),
                ('site_name2', models.CharField(max_length=55)),
                ('site_logo', models.ImageField(upload_to='logo/')),
                ('up_time', models.CharField(max_length=55)),
                ('countries_count', models.CharField(max_length=55)),
                ('servers_count', models.CharField(max_length=55)),
                ('footer_text', models.CharField(max_length=155)),
                ('footer_developer_name_text', models.CharField(max_length=55)),
            ],
        ),
    ]
