# Generated by Django 5.2.2 on 2025-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_payment_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='payment_card_name',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
