# Generated by Django 5.2.2 on 2025-09-16 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_payment_card_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='frequentlyaskedquestions',
            options={'verbose_name': 'FrequentlyAskedQuestion', 'verbose_name_plural': 'FrequentlyAskedQuestions'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'SiteSetting', 'verbose_name_plural': 'SiteSettings'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='core.frequentlyaskedquestions', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='is phone verified'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is staff'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=32, unique=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=55, verbose_name='telegram id'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='question',
            field=models.CharField(max_length=255, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='countries_count',
            field=models.CharField(max_length=55, verbose_name='countries count'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='established_year_for_about_us',
            field=models.CharField(max_length=55, verbose_name='established_year_for_about_us'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature1_for_about_us',
            field=models.CharField(max_length=55, verbose_name='feature1_for_about_us'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature2_for_about_us',
            field=models.CharField(max_length=55, verbose_name='feature2_for_about_us'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature3_for_about_us',
            field=models.CharField(max_length=55, verbose_name='feature3_for_about_us'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='feature4_for_about_us',
            field=models.CharField(max_length=55, verbose_name='feature4_for_about_us'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(max_length=155, verbose_name='footer text'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='payment_card',
            field=models.CharField(max_length=155, verbose_name='payment card number'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='payment_card_name',
            field=models.CharField(max_length=155, verbose_name='payment card owner name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='servers_count',
            field=models.CharField(max_length=55, verbose_name='servers count'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.URLField(verbose_name='site logo svg'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name1',
            field=models.CharField(max_length=55, verbose_name='site name1'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name2',
            field=models.CharField(max_length=55, verbose_name='site name2'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_Channel_id_link',
            field=models.URLField(verbose_name='telegram_Channel_id_link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_bot_id_link',
            field=models.URLField(verbose_name='telegram_bot_id_link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_support_id_link',
            field=models.URLField(verbose_name='telegram_support_id_link'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='up_time',
            field=models.CharField(max_length=55, verbose_name='servers uptime'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='users_count_for_about_us',
            field=models.CharField(max_length=55, verbose_name='users_count_for_about_us'),
        ),
    ]
