# Generated by Django 5.2.2 on 2025-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='established_year_for_about_us',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature1_for_about_us',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature2_for_about_us',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature3_for_about_us',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='feature4_for_about_us',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='users_count_for_about_us',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
