# Generated by Django 5.2.2 on 2025-09-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(upload_to='logo/', verbose_name='site logo'),
        ),
    ]
