# Generated by Django 5.2.2 on 2025-09-13 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_answer_frequentlyaskedquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='core.frequentlyaskedquestions'),
            preserve_default=False,
        ),
    ]
