# Generated by Django 5.2.2 on 2025-09-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sitesettings_site_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_developer_name_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_text',
        ),
    ]
