# Generated by Django 5.2.2 on 2025-09-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_sitesettings_footer_developer_name_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
