# Generated by Django 5.2.2 on 2025-09-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sitesettings_footer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_Channel_id_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_bot_id_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_support_id_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
