# Generated by Django 5.2.2 on 2025-09-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_telegram_channel_id_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='frequentlyaskedquestions',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
