# Generated by Django 5.2.2 on 2025-09-18 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('subs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_picture', models.ImageField(upload_to='payment/', verbose_name='payment picture')),
                ('total_price', models.PositiveIntegerField(verbose_name='total price')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='order')),
                ('subs', models.ManyToManyField(blank=True, related_name='payments', to='subs.subscriptions', verbose_name='subs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
