# Generated by Django 5.2.2 on 2025-09-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
