# Generated by Django 5.2.2 on 2025-09-16 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_is_used'),
        ('subs', '0002_alter_subscriptionlinks_day_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sub',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subs.subscriptions'),
        ),
    ]
