# Generated by Django 5.2.2 on 2025-09-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_sub'),
        ('subs', '0002_alter_subscriptionlinks_day_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='sub',
        ),
        migrations.AddField(
            model_name='payment',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='payments', to='subs.subscriptions'),
        ),
    ]
