# Generated by Django 5.2.2 on 2025-09-16 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options_alter_orderitem_options_and_more'),
        ('payment', '0004_remove_payment_sub_payment_subs'),
        ('subs', '0004_alter_subscriptionlinks_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='is used'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_picture',
            field=models.ImageField(upload_to='payment/', verbose_name='payment picture'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='payments', to='subs.subscriptions', verbose_name='subs'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='total price'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
