# Generated by Django 5.2.2 on 2025-09-18 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=55, verbose_name='Display name')),
                ('user_profile', models.ImageField(upload_to='comments/', verbose_name='User profile image')),
                ('user_city', models.CharField(max_length=55, verbose_name='User city')),
                ('text', models.TextField(verbose_name='Comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='Discount value')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Name')),
                ('time_limit', models.CharField(help_text='unlimited: 0', max_length=155, verbose_name='Time limit')),
                ('time_limit_NUM', models.IntegerField(help_text='unlimited: 0', verbose_name='Time limit (numeric)')),
                ('traffic_limit', models.CharField(help_text='unlimited: 0', max_length=155, verbose_name='Traffic limit')),
                ('traffic_limit_NUM', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Traffic limit (numeric)')),
                ('device_connections_limit', models.CharField(help_text='unlimited: 0', max_length=155, verbose_name='Device connections limit')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('feature1', models.CharField(blank=True, max_length=155, verbose_name='Feature 1')),
                ('feature2', models.CharField(blank=True, max_length=155, verbose_name='Feature 2')),
                ('feature3', models.CharField(blank=True, max_length=155, verbose_name='Feature 3')),
                ('is_special', models.BooleanField(default=False, verbose_name='Is special')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_products', to='shop.discount', verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
