# Generated by Django 5.2.2 on 2025-09-12 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=55)),
                ('user_profile', models.ImageField(upload_to='comments/')),
                ('user_city', models.CharField(max_length=55)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('time_limit', models.CharField(help_text='unlimited: 0', max_length=155)),
                ('traffic_limit', models.CharField(help_text='unlimited: 0', max_length=155)),
                ('device_connections_limit', models.CharField(help_text='unlimited: 0', max_length=155)),
                ('price', models.PositiveIntegerField()),
                ('feature1', models.CharField(blank=True, max_length=155)),
                ('feature2', models.CharField(blank=True, max_length=155)),
                ('feature3', models.CharField(blank=True, max_length=155)),
                ('is_special', models.BooleanField(default=False)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_products', to='shop.discount')),
            ],
        ),
    ]
