# Generated by Django 5.2.2 on 2025-09-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('time_limit', models.CharField(max_length=155)),
                ('traffic_limit', models.CharField(max_length=155)),
                ('device_connections_limit', models.CharField(max_length=155)),
                ('feature1', models.CharField(max_length=155)),
                ('feature2', models.CharField(max_length=155)),
                ('feature3', models.CharField(max_length=155)),
                ('is_special', models.BooleanField(default=False)),
            ],
        ),
    ]
