# Generated by Django 5.2.2 on 2025-09-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='time_limit_NUM',
            field=models.IntegerField(default=1, help_text='unlimited: 0', max_length=155),
            preserve_default=False,
        ),
    ]
