# Generated by Django 5.2.2 on 2025-09-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=55)),
                ('user_profile', models.ImageField(upload_to='comments/')),
                ('user_city', models.CharField(max_length=55)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='device_connections_limit',
            field=models.CharField(help_text='unlimited: 0', max_length=155),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature1',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature2',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature3',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_limit',
            field=models.CharField(help_text='unlimited: 0', max_length=155),
        ),
        migrations.AlterField(
            model_name='product',
            name='traffic_limit',
            field=models.CharField(help_text='unlimited: 0', max_length=155),
        ),
    ]
