# Generated by Django 5.2.2 on 2025-09-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_time_limit_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='traffic_limit_NUM',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
