# Generated by Django 5.2.2 on 2025-09-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_traffic_limit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='time_limit_NUM',
            field=models.IntegerField(help_text='unlimited: 0'),
        ),
    ]
