# Generated by Django 5.2.2 on 2025-09-16 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_time_limit_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Discount', 'verbose_name_plural': 'Discounts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='display_name',
            field=models.CharField(max_length=55, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Comment text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_city',
            field=models.CharField(max_length=55, verbose_name='User city'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_profile',
            field=models.ImageField(upload_to='comments/', verbose_name='User profile image'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Discount value'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='device_connections_limit',
            field=models.CharField(help_text='unlimited: 0', max_length=155, verbose_name='Device connections limit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_products', to='shop.discount', verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature1',
            field=models.CharField(blank=True, max_length=155, verbose_name='Feature 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature2',
            field=models.CharField(blank=True, max_length=155, verbose_name='Feature 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature3',
            field=models.CharField(blank=True, max_length=155, verbose_name='Feature 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Is special'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=155, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_limit',
            field=models.CharField(help_text='unlimited: 0', max_length=155, verbose_name='Time limit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time_limit_NUM',
            field=models.IntegerField(help_text='unlimited: 0', verbose_name='Time limit (numeric)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='traffic_limit',
            field=models.CharField(help_text='unlimited: 0', max_length=155, verbose_name='Traffic limit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='traffic_limit_NUM',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Traffic limit (numeric)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
