# Generated by Django 5.2.13 on 2026-07-11 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=6, unique=True, verbose_name='reference id')),
                ('requested_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='requested amount')),
                ('bonus_amount', models.PositiveIntegerField(default=0, verbose_name='bonus amount')),
                ('payable_amount', models.PositiveIntegerField(verbose_name='payable amount')),
                ('payment_card_number', models.CharField(max_length=32, verbose_name='payment card number')),
                ('payment_card_owner', models.CharField(max_length=155, verbose_name='payment card owner')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='bot_receipts/', verbose_name='receipt image')),
                ('receipt_text', models.TextField(blank=True, verbose_name='receipt text')),
                ('receipt_link', models.URLField(blank=True, verbose_name='receipt link')),
                ('transaction_id', models.CharField(blank=True, max_length=120, verbose_name='transaction id')),
                ('admin_note', models.TextField(blank=True, verbose_name='admin note')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_bot_payments', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Bot payment request',
                'verbose_name_plural': 'Bot payment requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('top_up', 'Top up'), ('adjustment', 'Adjustment'), ('spend', 'Spend')], max_length=20, verbose_name='kind')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('previous_balance', models.PositiveIntegerField(verbose_name='previous balance')),
                ('new_balance', models.PositiveIntegerField(verbose_name='new balance')),
                ('reference_code', models.CharField(blank=True, max_length=120, verbose_name='reference code')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='botapi.botpaymentrequest', verbose_name='request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Wallet transaction',
                'verbose_name_plural': 'Wallet transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='botpaymentrequest',
            name='approved_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_source', to='botapi.wallettransaction', verbose_name='approved transaction'),
        ),
        migrations.CreateModel(
            name='BotRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=155, verbose_name='endpoint')),
                ('method', models.CharField(max_length=12, verbose_name='method')),
                ('ip_address', models.CharField(blank=True, max_length=64, verbose_name='ip address')),
                ('status_code', models.PositiveIntegerField(verbose_name='status code')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_request_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Bot request log',
                'verbose_name_plural': 'Bot request logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['endpoint', 'created_at'], name='botapi_botr_endpoin_f2493e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=128, unique=True, verbose_name='token hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='last used at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('telegram_user_id', models.CharField(blank=True, max_length=64, verbose_name='telegram user id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Bot session',
                'verbose_name_plural': 'Bot sessions',
                'indexes': [models.Index(fields=['token_hash'], name='botapi_bots_token_h_f5cd65_idx'), models.Index(fields=['expires_at'], name='botapi_bots_expires_f12d41_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['kind', 'created_at'], name='botapi_wall_kind_dc3466_idx'),
        ),
        migrations.AddIndex(
            model_name='botpaymentrequest',
            index=models.Index(fields=['reference_id'], name='botapi_botp_referen_2b935a_idx'),
        ),
        migrations.AddIndex(
            model_name='botpaymentrequest',
            index=models.Index(fields=['status', 'created_at'], name='botapi_botp_status_2a4854_idx'),
        ),
    ]
