# Generated by Django 5.2.2 on 2025-09-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_telegram_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
