# Generated by Django 5.2.2 on 2025-09-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
